# analysis_options.yaml
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "lib/**.reflectable.dart"
    - "build/**"
    - ".dart_tool/**"

  errors:
    public_member_api_docs: ignore
    unnecessary_brace_in_string_interps: warning
    deprecated_member_use_from_same_package: warning

linter:
  rules:
    avoid_print: error
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_pub_dependencies: true
    unawaited_futures: error